### ISSUE TITLE
Resizing and moving window at same time

### ISSUE THREAD

**Issue by vladdeSV** [zenangst/MouseDef#3]
**Issue**: Resizing and moving window causes window to frenetically jiggle. Upon releasing all buttons (<kbd>⌘</kbd>, <kbd>⇧</kbd>, and <kbd>fn</kbd>) the windows continues to jiggle when moving the mouse and does not stop until *MouseDef.app* is exited.

I used *Karabiner-EventView.app* to display which buttons are pressed and released in demo below.

![demo](https://i.imgur.com/13kioMx.gif)

**Reproduce**:
- Hold <kbd>⌘</kbd>, <kbd>⇧</kbd>, and <kbd>fn</kbd> over a window, and move mouse
- Release all buttons, and move mouse
- (Quit *MouseDef.app* to stop window from moving)

**Extra info**:
- *MouseDef.app* `v0.0.2`
- MacBook Pro, macOS Catalina `v10.15.4`

**Comment by vladdeSV** [comment]
Huh, that's odd. GIF is not showing.

Permalink: https://i.imgur.com/13kioMx.gif

**Comment by zenangst** [comment]
@vladdeSV thanks for reporting this. I have been seeing this once or twice but I have yet to solve it properly. I'm guessing we are not monitoring changes in flags correctly. Seems like we are opting out on certain scenarios which is causing the monitoring to get locked in active state.

I'll do some more digging and get back to you :)

**Comment by zenangst** [comment]
@vladdeSV shipping a new version to Apple to be notarized as we speak. A new version should be available shortly.

**Comment by zenangst** [comment]
@vladdeSV a new version is out: https://github.com/zenangst/MouseDef/releases/tag/0.0.3

Thanks again for reporting this issue :)
