### ISSUE TITLE
Moving window slowly favour left and down directions

### ISSUE THREAD

**Issue by vladdeSV** [zenangst/MouseDef#5]
**Issue**: When moving a window slowly with <kbd>fn</kbd><kbd>⌘</kbd>, the distance the window travels left and downwards is almost double the pointer speed. Moving the window right and upwards the window does not move until a the cursor moves at a fast enough speed.

I cannot notice this behaviour when moving the cursor at faster speeds (regular usage).

![img](https://i.imgur.com/2Zp5PCV.gif)

**Extra**:
- *MouseDef.app* `v0.0.3`
- MacBook Pro, macOS Catalina `v10.15.4`

**Comment by zenangst** [comment]
@vladdeSV interesting issue, perhaps the algoritm doesn't take into account the cursors size or something like that. I'll do some digging to see if I can't get to the bottom of this. Thanks again for reporting the issues that you find, helps a lot that you make them so detailed! ❤️

**Comment by zenangst** [comment]
Hey @vladdeSV, I did some refactoring and improved the move and resize algorithms. Mind taking the new version `0.0.4` for a spin - https://github.com/zenangst/MouseDef/releases/tag/0.0.4

**Comment by vladdeSV** [comment]
﻿
﻿Awesome! I'll try this out at Monday, when I'm back at the office.

Sent from my rymdtelefon

On 21 May 2020, at 18:58, Christoffer Winterkvist <notifications@github.com> wrote:

﻿
Hey @vladdeSV, I did some refactoring and improved the move and resize algorithms. Mind taking the new version 0.0.4 for a spin - https://github.com/zenangst/MouseDef/releases/tag/0.0.4

**Comment by vladdeSV** [comment]
Works wonders!

Thanks @zenangst 😃

**Comment by zenangst** [comment]
@vladdeSV awesome, I saw a pretty drastic improvement myself. Thanks for reporting back! :)
Don't hesitate to report any stuff in the future if they appear, cheers!
